dj-diplom-master/shop/basket/urls.py
from django.urls import path
from basket import views

app_name = "basket"

urlpatterns = [
    path('cart/', views.cart_view, name='cart'),
    path('add/<product_id>', views.add_cart, name='add_cart'),
    path('remove/<product_id>', views.remove_cart, name='remove_cart'),
    path('cart/order', views.order_view, name='order'),
]

dj-diplom-master/shop/main/urls.py
from django.urls import path
from main.views import article_view, index, smart_view, phone_view, extra_view

app_name = "main"

urlpatterns = [
    path('', index, name='index'),

    # path('smartphones/', smart_view, name = 'smarts'),
    path('?page=<page_num>/', smart_view),
    path('phone/', phone_view, name='phone'),
    path('articles/', extra_view, name="extra"),
    path('<int:id>/<slug:slug>/', phone_view, name='product_detail'),
    path('category/<slug:category_slug>/', smart_view,
         name='product_list_by_category'),
    path('articles/article/<int:id>', article_view, name='article_detail')
]

dj-diplom-master/shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop.settings import STATIC_URL
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basket.urls', namespace="basket")),
    path('', include('registration.urls')),
    path('', include('main.urls', namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dj-diplom-master/shop/basket/models.py
from django.db import models
# from django.contrib.auth.models import User
from main.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created', )
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return "Заказ {}".format(self.id)

    # def get_total_cost(self):
    #     return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE,
                              related_name="items")
    product = models.ForeignKey(Product, on_delete=models.CASCADE,
                                related_name="order_items")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return "{}".format(self.order)

    def get_cost(self):
        return self.price * self.quantity

dj-diplom-master/shop/basket/forms.py
from basket.models import Order
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='Количество')
    override = forms.BooleanField(initial=False, required=False, widget=forms.HiddenInput)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'address', 'postal_code', 'city')

dj-diplom-master/shop/basket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from basket.models import Order, OrderItem
from .cart import Cart
from .forms import CartAddForm, OrderForm


def cart_view(request):
    cart = Cart(request)
    quantity_products = cart.len()
    form = CartAddForm()
    template = "basket/cart.html"
    return render(request, template, {'cart': cart,
                                      'total': quantity_products,
                                      'form': form, })


@require_POST
def add_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override=cd['override'])
    return redirect("basket:cart")


@require_POST
def remove_cart(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect("basket:cart")


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'basket/detail.html', {'cart': cart})


def order_view(request):
    cart = Cart(request)
    form = OrderForm()
    if request.method == "POST":
        form = OrderForm(request.POST)
        if form.is_valid:
            order = form.save()
            for i in cart:
                OrderItem.objects.create(order=order,
                                         product=i['product'],
                                         price=i["price"],
                                         quantity=i["quantity"])
            cart.clear()
            return render(request, 'basket/created.html', {'order': order})
    else:
        return render(request, 'basket/order.html', {'form': form})

dj-diplom-master/shop/templates/basket/cart.html
{% extends "base.html" %}
{% load static %}

{% block title %}Корзина{% endblock %}
{% block content %}

<div class="container mt-3">

  <div class="row">
    <div class="col-lg-6 col-md-9 col-sm-12 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Ваша корзина</span>
        <span class="badge badge-secondary badge-pill">{{total}}</span>
      </h4>
      <ul class="list-group mb-3">
      {% for i in cart  %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <a href="{{ i.product.get_absolute_url }}">
            <h6 class="my-0">{{i.product}}</h6>
            </a>
            <small class="text-muted">Количество: {{ i.quantity }}</small>
          </div>  
            <span class="text-muted">{{ i.price }}</span>

            <span class="text-muted">{{ i.total_price }}</span>
            <form action="{% url "basket:remove_cart" i.product.id %}" method="post">
            <input type="submit" value="Удалить">
            {% csrf_token %}
            </form>             
        </li>
        {% endfor %}
      </ul>

      <form class="card p-2" action="{% url "basket:order" %}">
        <button type="submit" class="btn btn-secondary">Заказать</button>
      </form>
    </div>
  </div>

</div>
{% endblock %}

dj-diplom-master/shop/templates/basket/created.html
{% extends "base.html" %}
{% load static %}

{% block title %}Спасибо за заказ!{% endblock %}
{% block content %}

<div class="container mt-3">

    <h1 class="h3 mb-3 font-weight-normal">Ваш заказ был успешно создан. Номер заказа: {{order.id}}</h1>

</div>
{% endblock %}

dj-diplom-master/shop/templates/basket/order.html
{% extends "base.html" %}
{% load static %}

{% block title %}Оформление заказа{% endblock %}
{% block content %}

<div class="container mt-3">


    <h1 class="h3 mb-3 font-weight-normal">Укажите ваши данные по доставке товара</h1>
    <br>
    <div class="row">
      <form class="card p-2" method ="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-secondary">Оплатить</button>
      </form>
    </div>


</div>
{% endblock %}