dj-diplom-master/shop/basket/urls.py
from django.urls import path
from basket import views

app_name = "basket"

urlpatterns = [
    path('cart/', views.cart_view, name='cart'),
    path('add/<product_id>', views.add_cart, name='add_cart'),
    path('remove/<product_id>', views.remove_cart, name='remove_cart'),
    path('cart/order', views.order_view, name='order'),
]

dj-diplom-master/shop/main/urls.py
from django.urls import path
from main.views import article_view, index, smart_view, phone_view, extra_view

app_name = "main"

urlpatterns = [
    path('', index, name='index'),

    # path('smartphones/', smart_view, name = 'smarts'),
    path('?page=<page_num>/', smart_view),
    path('phone/', phone_view, name='phone'),
    path('articles/', extra_view, name="extra"),
    path('<int:id>/<slug:slug>/', phone_view, name='product_detail'),
    path('category/<slug:category_slug>/', smart_view,
         name='product_list_by_category'),
    path('articles/article/<int:id>', article_view, name='article_detail')
]

dj-diplom-master/shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop.settings import STATIC_URL
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basket.urls', namespace="basket")),
    path('', include('registration.urls')),
    path('', include('main.urls', namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dj-diplom-master/shop/main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Article(models.Model):
    name = models.CharField(max_length=50)
    text = models.TextField()
    product = models.ForeignKey("Product", on_delete=models.DO_NOTHING)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:article_detail", args=[self.id])


class Category(models.Model):
    name = models.CharField(max_length=50, db_index=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ("name",)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:product_list_by_category", args=[self.id])


class Product(models.Model):
    category = models.ForeignKey(Category, verbose_name="Категория товара",
                                 on_delete=models.CASCADE)
    name = models.CharField(verbose_name="Название", max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                verbose_name="Стоимость")
    image = models.ImageField(upload_to='products', blank=True)
    description = models.TextField(blank=True, verbose_name="Описание")
    created = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = "Product"
        verbose_name_plural = "Products"
        ordering = ("name",)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("main:product_detail", args=[self.id, self.slug])


class Review(models.Model):
    text = models.TextField(verbose_name="Отзыв")
    name = models.ForeignKey(User, verbose_name="Имя",
                             on_delete=models.CASCADE,
                             related_name="names")
    product = models.ForeignKey(Product, verbose_name="Товар",
                                on_delete=models.CASCADE,
                                related_name="reviews")
    score = models.IntegerField(default=1)

    class Meta:
        verbose_name = "Review"
        verbose_name_plural = "Reviews"

    def __str__(self):
        return str(self.product.name) + ' ' + self.text[:10]

dj-diplom-master/shop/main/forms.py
from django import forms
from main.models import Review, Article
from ckeditor.widgets import CKEditorWidget


class ReviewForm(forms.ModelForm):
    text = forms.CharField(label='Содержание', required=False)
    score = forms.IntegerField(max_value=5, min_value=1, required=True)

    class Meta:
        model = Review
        fields = ('name', 'score')


class ArticleForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorWidget(),
                           label='Содержание', required=False)

    class Meta:
        model = Article
        fields = ('name', 'text', 'product')

dj-diplom-master/shop/main/views.py
from django.contrib.auth.models import User
from main.forms import ReviewForm
from basket.forms import CartAddForm
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from main.models import Article, Category, Product, Review
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def get_cart_form():
    cart_product_form = CartAddForm()
    return cart_product_form


def index(request):
    template = "main/index.html"
    categories = Category.objects.all()
    product = Product.objects.all()
    articles = Article.objects.all().order_by('-created')[:3]
    context = {'cart_product_form': get_cart_form(),
               'categories': categories,
               "product_mobile": product.filter(category_id=1, available=True).order_by('-created')[:3],
               "product_dif": product.filter(category_id=2, available=True).order_by('-created')[:3],
               'articles': articles, }
    return render(request, template, context)


def smart_view(request, category_slug=None):
    template = "main/smartphones.html"
    category = None
    categories = Category.objects.all()
    product = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        product = Product.objects.filter(category=category)

    paginate_by = 1
    current_page = Paginator(product, paginate_by)
    page = request.GET.get('page')
    try:
        products = current_page.page(page)
    except PageNotAnInteger:
        products = current_page.page(1)
    except EmptyPage:
        products = current_page.page(current_page.num_pages)

    context = {
        'category': category,
        'categories': categories,
        'products': products,
        'product': product,
        "page": page,
        'cart_product_form': get_cart_form()
    }
    return render(request, template, context)


def phone_view(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    revform = ReviewForm
    product_review = Review.objects.filter(product_id=id)

    if request.method == "POST":
        revform = ReviewForm(request.POST)
        if revform.is_valid:
            text = request.POST.get('text')
            score = request.POST.get('score')
            product_name = Product.objects.get(id=id)
            reviews = Review(name=request.user, text=text, score=score,
                             product=product_name)
            reviews.save()
            return redirect(request.build_absolute_uri())

    else:
        return render(request, 'main/phone.html',
                      {'product': product,
                       'cart_product_form': get_cart_form(),
                       'revform': revform,
                       'product_review': product_review,
                       'range': range(1, 6), })


def extra_view(request):
    template = 'main/empty_section.html'
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, template, context)


def article_view(request, id):
    template = 'main/article.html'
    article = Article.objects.get(id=id)
    product = Product.objects.all()
    context = {'article': article,
               'product':product}
    return render(request, template, context)

dj-diplom-master/shop/templates/main/article.html
{% extends "base.html" %}
{% load static %}

{% block title %}Пусто{% endblock %}
{% block content %}

<main role="main">

  <div class="container">
    <!-- Example row of columns -->
    {% comment %} <a href = {% url "main:article"%}<div class="alert alert-dark" role="alert"> {% endcomment %}
      <h5><p>{{article.name|safe}}</p></h5>
      <p>{{article.text|safe}}
    </a>

    </div>

    <h7> Возможно вас заинтересует:</h7>
    <br>
        <a href={{ product.get_absolute_url }}> {{article.product.name}}</a>
  </div> <!-- /container -->


</main>

{% endblock %}

dj-diplom-master/shop/templates/main/empty_section.html
{% extends "base.html" %}
{% load static %}

{% block title %}Пусто{% endblock %}
{% block content %}

<main role="main">

  <div class="container">
    <!-- Example row of columns -->


    <div class="alert alert-dark" role="alert">
      Тут пока ничего нет!
    </div>


  </div> <!-- /container -->

</main>

{% endblock %}

dj-diplom-master/shop/templates/main/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}Главная{% endblock %}
{% block content %}
<main role="main">

  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Добро пожаловать на сайт просто магазина</h1>
      <p>Последние статьи:</p>
      {% for article in articles %}
      <a href={{article.get_absolute_url}}> {{article.name}}</a>
      <p>{% endfor %}</p>
     <p>Лучшие мобилы только у нас:</p> 
    </div>
  </div>


  <div class="container -fluid">
    <div class="row">
    {% for product in product_mobile %}
      <div class="col-md-4">
      <br>
      <h2>{{ product.name }}</h2>
      <br>
        <a href={{product.get_absolute_url}}>
          <img src="{{ product.image.url }}" width="180">
          </a>
      <br>
      <p style="margin-left: 2.9em">{{product.price}} руб <p>

        <form method="post" action="{%url 'basket:add_cart' product.id %}">
        {{cart_product_form}}
        {% csrf_token %}
        <br>
          <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
        </form>
        </div>
      {% endfor %}
      </div>
    </div>


  <div class="jumbotron">
    <div class="container">
      <h1 class="display-4">Не знаете что одеть летом?</h1>
      <p>Вот что мы можем предложить:</p>
    </div>
  </div>


  <div class="container mb-5">

    <div class="row">

      <div class="col-md-4">
     {% for product in product_dif %}
      <br>
      <h2>{{ product.name }}</h2>
      <br>
        <a href={{product.get_absolute_url}}>
          <img src="{{ product.image.url }}" class="preview" width="180">
          </a>
      <br>
      <p>{{product.price}} руб <p>
      <br>
        <form method="post" action="{%url 'basket:add_cart' product.id %}">
        {{cart_product_form}}
        {% csrf_token %}
        <br>
          <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
        </form>
        </div>
      {% endfor %}
      </div>

    </div>
  </div> 

</main>
{% endblock %}

dj-diplom-master/shop/templates/main/phone.html
{% extends "base.html" %}
{% load static %}
{% load stars %}

{% block title %}{{product.name}}{% endblock %}
{% block content %}

<main role="main">

  <div class="container mt-3">
    <div class="row">
      <div class="col-md-12">
        <h2>{{product.name}}</h2> 
        <img src="{{product.image.url}}" width="160">   
        <p>{{product.price}} руб.</p>  

        <form method="post" action="{% url 'basket:add_cart' product.id %}">
        {{cart_product_form}}
        {% csrf_token %}
          <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
        </form>
        {{ product.description|linebreaks }}

      </div>
    </div>
    <hr>
    {{tet}}
    {% if product_review %}
    {% for review in product_review %}
    {{review.score|stars_filter}}<span>{{review.name}}</span>
    
    <p>{{review.text}}</p>
    {% endfor %}
    {% else %}
    <h5> Тут ещё нет отзовов </h5>
    {% endif %}

    <hr>

    <div class="row">
      <div class="col-lg-6 col-md-8 col-sm-12">

        {% if request.user.is_authenticated %}
        <h4>Оставьте отзыв:</h4>
        <form action=" " method="post">
          <label for="name"><h5>{{ user.username }}</h5></label>
          <br>
          
          <div class="form-group">
            <label for="content">Содержание</label>
            {{ revform.text }}
          </div>          
          <br>
          {{ revform.score }}
            <br>
<div class="form-group">

    {% for num in range %}
   
    <div class="form-check">
            <input class="form-check-input" type="radio" name="score" id="mark1" value="{{num}}">
            <label class="form-check-label" for="mark1">
            {{ num }}
            </label>
            </div>
    {% endfor %}

          </div>
          {% csrf_token %}
          <input type="submit" class="btn btn-primary"></input>
        </form>
      </div>
      {% else %}
      <h4> Незарегистрированные пользователи не могут оставить свой отзыв  </h4>
      {% endif %} 
    </div>

  </div> <!-- /container -->


</main>
{% endblock %}

dj-diplom-master/shop/templates/main/smartphones.html
{% extends "base.html" %}
{% load static %}

{% block title %}Телефоны{% endblock %}
{% block content %}

<main role="main">

  <div class="container">
    <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Все товары{% endif %}</h1>
    
    <br>

    <div class="row">
    {% for p in products %}
    
      <div class="item">
        <h2><a href="{{ p.get_absolute_url }}">{{p.name}}</a></h2>

        <a href="{{ p.get_absolute_url }}">
        <img src="{{p.image.url}}" width="180">
        </a>
        <p style="margin-left: 2.9em">{{p.price}} руб <p>

        <form method="post" action="{%url 'basket:add_cart' p.id %}">
        {{cart_product_form}}
        {% csrf_token %}
          <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
        </form> 
        
      </div>         
    {% endfor %}
    <br>
    </div>  
 
    <div class="row" >
      <ul class="pagination" > 
      <li style='letter-spacing : 0.5em'>
        {% if products.has_previous %}
       <a href="?page={{ products.previous_page_number }}"> < </a>
        {% else %}
         <a href=""> </a>
        {% endif %}
        {%for page in products.paginator.page_range%}
          {% if page == products.number %}
            <span class="curent"> <a href = "?page={{ page }}"> {{page}} </a></span>
            {% else %}
            <a href = "?page={{ page }}"> {{page}} </a>
          {% endif %}
        {% endfor %}
        {% if products.has_next %}
        <a href="?page={{ products.next_page_number }}"> > </a>
        {% else %}
        <a> </a>
        {% endif %}
        </li>
      </ul> 
  </div> 
</main>

{% endblock %}