dj-diplom-master/shop/basket/urls.py
from django.urls import path
from basket import views

app_name = "basket"

urlpatterns = [
    path('cart/', views.cart_view, name='cart'),
    path('add/<product_id>', views.add_cart, name='add_cart'),
    path('remove/<product_id>', views.remove_cart, name='remove_cart'),
    path('cart/order', views.order_view, name='order'),
]

dj-diplom-master/shop/main/urls.py
from django.urls import path
from main.views import article_view, index, smart_view, phone_view, extra_view

app_name = "main"

urlpatterns = [
    path('', index, name='index'),

    # path('smartphones/', smart_view, name = 'smarts'),
    path('?page=<page_num>/', smart_view),
    path('phone/', phone_view, name='phone'),
    path('articles/', extra_view, name="extra"),
    path('<int:id>/<slug:slug>/', phone_view, name='product_detail'),
    path('category/<slug:category_slug>/', smart_view,
         name='product_list_by_category'),
    path('articles/article/<int:id>', article_view, name='article_detail')
]

dj-diplom-master/shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop.settings import STATIC_URL
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('basket.urls', namespace="basket")),
    path('', include('registration.urls')),
    path('', include('main.urls', namespace="main")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dj-diplom-master/shop/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" >
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <style>
   li {
    list-style-type: none; /* Убираем маркеры */
   }
   </style>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static "bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "main.css" %}">
</head>
<body class="" data-gr-c-s-loaded="true">

<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href={% url 'main:index' %}>Просто магазин</a>
  <img src="{% static "logo.svg" %}" alt="" width="42" height="42">
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href={% url 'main:index' %}>
          Главная</a>
      </li>


      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="dropdown01"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Категория</a>
          
            <div class="dropdown-menu" aria-labelledby="dropdown01">  
            {% for c in categories %} 
            <a class="dropdown-item" href="{{ c.get_absolute_url }}">
              {{c.name}}
            </a>
            {% endfor %}
            </div>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href={% url 'main:extra' %}>
          Статьи</a>
      </li>

    </ul>


    <a class="btn btn-outline-success my-2 my-sm-0" role="button"
       href= {% url 'basket:cart' %}>
      Корзина</a>

      <li class="nav-item dropdown">
      {% if request.user.is_authenticated %}
        <a class="nav-link dropdown" href="#" id="dropdown01"
           data-toggle="dropdown">
          {{user.username}}
          </a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href= {% url 'logout' %}>
            Выйти</a>
        </div> {% else %}
      </li>

   
    <a class="btn btn-outline-success my-2 my-sm-0" role="button"
       href= {%url 'login' %}>
      Войти</a>
    {% endif %}
</div>
</nav>

<br>
<div class="container">{% block content %}{% endblock %}</div>

<hr>
<footer class="container">
  <p>© Просто магазин 2018</p>
</footer>

<script src="{% static "jquery-3.3.1.slim.min.js" %}"></script>
<script src="{% static "popper.min.js" %}"></script>
<script src="{% static "bootstrap.min.js" %}"></script>

</body>
</html>